# Generated by Django 5.0.7 on 2024-07-22 19:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bridgesAPI', '0001_initial'),
    ]
operations = [
        migrations.RunSQL(
            sql='SELECT 1;',  
            reverse_sql='SELECT 1;', 
        ),
]